---
# tasks file for ec2

- name: K8s Master Node creation
  ec2_instance:
          name: "K8s-Masternode"
          profile: aditya
          security_group: "{{ sg }}"
          key_name: "{{ key }}"
          instance_type: "{{ type }}"
          image_id: "{{ image }}"
          region: "{{ region }}"
          wait: yes
          wait_timeout: 15
          vpc_subnet_id: "{{ subnet }}"
  register: master
- name: Updating local Inventory
  lineinfile:
          path: '{{ inventory_path }}'
          regexp: '^[slavenode]'
          line: '{{ master.instances[0].public_ip_address }}  ansible_private_key_file={{ key_path }}  ansible_ssh_user=ec2-user'
          insertbefore: '[slavenode]'

- name: K8s Worker Node1 creation
  ec2_instance:
          name: "K8s-SlaveNode 1"
          security_group: "{{ sg }}"
          profile: aditya
          key_name: "{{ key }}"
          instance_type: "{{ type }}"
          image_id: "{{ image }}"
          region: "{{ region }}"
          wait: yes
          wait_timeout: 15
          vpc_subnet_id: "{{ subnet }}"  
  register: slave1

- name: Updating local Inventory
  lineinfile:
          path: '{{ inventory_path }}'
          regexp: '^[slavenode]'
          line: '{{ slave1.instances[0].public_ip_address }}  ansible_private_key_file={{ key_path }}  ansible_ssh_user=ec2-user'
          insertafter: '[slavenode]'

- name: K8s Worker Node2 creation
  ec2_instance:
          name: "K8s-SlaveNode 2"
          profile: aditya
          security_group: "{{ sg }}"
          key_name: "{{ key }}"
          instance_type: "{{ type }}"
          image_id: "{{ image }}"
          region: "{{ region }}"
          wait: yes
          wait_timeout: 15
          vpc_subnet_id: "{{ subnet }}"  
  register: slave2

- name: Updating local Inventory
  lineinfile:
          path: '{{ inventory_path }}'
          regexp: '^[slavenode]'
          line: '{{ slave2.instances[0].public_ip_address }}  ansible_private_key_file={{ key_path }}  ansible_ssh_user=ec2-user'
          insertafter: '[slavenode]'

